import React from 'react';
import Head from 'next/head'
import Image from "next/image"
import Header from '../components/Header'
import MainHeader from '../components/MainHeader'
import SmallHeader from '../components/SmallHeader'
import Displays from '../components/Displays';
import Categories from '../components/Categories';
import FreeDelivery from '../components/FreeDelivery';
import { useState } from "react"
import AccountModal from '../components/AccountModal';
import HelpModal from '../components/HelpModal';

const Deliveries = ({products}) => {
    const [close, setClose] = useState(true)
  const [modal, setModal] = useState(true)
 
    return (
      <div className="bg-gray-200 h-screen w-screen overflow-x-hidden">
        <Head>
            <title>Wave Kenya | Online Shopping for Groceries, Electronics, Households, Clothings, Foods and so much more</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <SmallHeader />
            <MainHeader setClose={setClose} modal={modal} setModal={setModal} close={close}/>
            {!close && <AccountModal />}
            {!modal && <HelpModal />}
            <main className="max-w-5xl mx-auto ">
                <div className="flex flex-col space-y-4 my-10">
                    <div className="flex bg-white items-center justify-between rounded-md">
                        <Image className="rounded w-full h-full hover:scale-102 translation-all duration-100" height={300} width={1100} src="https://ke.jumia.is/cms/2022/W02/HP/Sliders/KE_Electronics_SuperSaver_Afcon_0122_S.jpg" alt="myimage" />
                    </div>
                    <div className="grid grid-flow-row-dense gap-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 bg-white rounded-sm py-5">
                        {products.slice(0, 12).map(({ image, category, description, price, title, id }) => (
                            <Displays 
                                id={id}
                                key={id}
                                image={image}
                                category={category}
                            />
                            ))}
                    </div>
                    <div className="grid grid-cols-12 space-x-3">
                        <div className="col-span-12 lg:col-span-3">
                            <Categories />
                        </div>
                        <div className="col-span-12 lg:col-span-9 bg-white rounded-sm mt-6 mx-4">
                            <span className="flex items-center justify-between border-b border-gray-200">
                                <p className="text-gray-80 text-md font-light p-2">FREE DELIVERY</p>
                                <p className="text-gray-80 text-md font-light hover:text-orange-400 p-3">Sort by :Popularity</p>
                            </span>
                            <div className="grid grid-flow-row-dense gap-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 bg-white rounded-md py-5">
                                {products.slice(0, 20).map(({ image, category, description, price, title, id }) => (
                                <FreeDelivery 
                                    id={id}
                                    key={id}
                                    image={image}
                                    category={category}
                                    description={description}
                                    price={price}
                                    title={title}
                                />
                            ))}
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then((res) => res.json())
  
  return {
    props: {
      products
    }
  }
}

export default Deliveries;
