import React from 'react';
import Header from '../components/Header';
import MainHeader from '../components/MainHeader';
import SmallHeader from '../components/SmallHeader';
import Head from 'next/head';
import Image from "next/image"
import Phones from '../components/Phones';
import Adverts from '../components/Adverts';
import Electronics from '../components/Electronics';
import {  SearchIcon, ChevronRightIcon, ShoppingCartIcon, ChatIcon, HeartIcon, SparklesIcon, ShieldCheckIcon, BadgeCheckIcon, ChatAlt2Icon } from '@heroicons/react/outline'
import {StarIcon} from '@heroicons/react/solid'
import AlsoLike from '../components/RecentlyLiked';
import Categories from '../components/Categories';
import { useState } from "react"
import AccountModal from '../../components/AccountModal';
import HelpModal from '../../components/HelpModal';

const OfficialStore = ({ products }) => {
    const [close, setClose] = useState(true)
  const [modal, setModal] = useState(true)
  return (
        <div className="bg-gray-100 overflow-x-hidden w-screen h-screen">
            <Head>
                <title>Wave Kenya | Official brands online Kenya: hp, lenovo, von, lg, kasuku, brum and so much more</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <SmallHeader />
            <MainHeader setClose={setClose} modal={modal} setModal={setModal} close={close}/>
            {!close && <AccountModal />}
            {!modal && <HelpModal />}
            <main className="grid grid-cols-12 w-full mx-auto my-10 px-16">
                <div className="max-w-5xl mt-10 col-span-12 mx-auto">
                    <div className="h-80">
                        <img className="rounded-sm w-full h-full" objectfit="contain" src="https://ke.jumia.is/cms/2022/W02/HP/Sliders/KE_Electronics_SuperSaver_Afcon_0122_S.jpg" alt="helloimage"/>
                    </div>
                    <Phones className="" products={products} />
                    <div className="flex mx-auto rounded-md my-4">
                        <div className="flex bg-white p-2 rounded space-x-2">
                            <div className="rounded-md">
                                <img className="rounded hover:scale-105 translation-all duration-100" src="https://ke.jumia.is/cms/2022/W02/HP/Sliders/KE_Electronics_SuperSaver_Afcon_0122_S.jpg" alt="myimage" />
                            </div>
                            <div className="rounded-md">
                                <img className="rounded hover:scale-105 translation-all duration-100" src="https://ke.jumia.is/cms/2022/W02/HP/Sliders/KE_Electronics_SuperSaver_Afcon_0122_S.jpg" alt="myimage" />
                            </div>
                        </div>
                   </div>
                   <Electronics products={products} />
                   <main className="grid grid-cols-12 space-x-1 mx-auto my-4 w-full">
                    {/* category */}
                    <Categories />
                    {/* returns & deliveries */}
                        <div className="flex flex-col col-span-9">
                            <Electronics products={products} />
                            <Electronics products={products} />
                            <Electronics products={products} />
                            <Electronics products={products} />
                            <Electronics products={products} />
                            <Electronics products={products} />
                        </div>
                        {/* delivery & returns */}
                        
                    </main>
                </div>
            </main>
        </div>
    );
};

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then((res) => res.json())
  
  return {
    props: {
      products
    }
  }
}

export default OfficialStore;
