import  Head  from "next/head"
import { useState } from "react"
import { useRouter } from "next/router"
import AccountModal from '../components/AccountModal';
import HelpModal from '../components/HelpModal';
import MainHeader from '../components/MainHeader';
import SmallHeader from '../components/SmallHeader';
import { ArchiveIcon, ChatAltIcon, ClockIcon, HeartIcon, MailIcon, TicketIcon, UserIcon} from '@heroicons/react/outline';
import Inbox from '../components/Inbox';
import Orders from '../components/Orders';
import SavedItems from '../components/SavedItems';
import Pending from '../components/Pending';
import WaveCredit from '../components/WaveCredit';

function orders() {
    const [close, setClose] = useState(true)
    const [modal, setModal] = useState(true)

    const [id, setId] = useState("")

    const handleOrder = (event) => {
        setOrder(prev => !prev)
        let targetId = event.target.id
        // console.log(targetId)
    }
  console.log(id) 
    const router = useRouter()

    return (
      <div className="bg-gray-100 overflow-x-hidden w-screen h-screen">
            <Head>
                <title>Wave Kenya | Orders</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SmallHeader />
            <MainHeader setClose={setClose} modal={modal} setModal={setModal} close={close}/>
            {!close && <AccountModal />}
            {!modal && <HelpModal />}
            <main className="grid grid-cols-12 space-x-3 max-w-6xl mx-auto my-5 px-8">
                {/* <div className="flex flex-col "> */}
                    <div className="flex flex-col col-span-3 rounded-sm shadow-gray-300 shadow-sm bg-white">
                        <span onClick={(event) => setId(event.target.id)} className="account_util" id="account">
                            <UserIcon className="h-5 text-gray-700 pointer-events-none"/>
                            <p className="account_util1 pointer-events-none">My Wave Account</p>
                        </span>
                        <span onClick={(event) => setId(event.target.id)} className="account_util" id="orders">
                            <ArchiveIcon className="h-5 text-gray-700 pointer-events-none"/>
                            <p className="account_util1 pointer-events-none">Orders</p>
                        </span>
                        <span onClick={(event) => setId(event.target.id)} className="account_util" id="inbox">
                            <MailIcon className="h-5 text-gray-700 pointer-events-none"/>
                            <p className="account_util1 pointer-events-none">Inbox</p>
                        </span>
                        <span onClick={(event) => setId(event.target.id)} className="account_util" id="pending">
                            <ChatAltIcon className="h-5 text-gray-700 pointer-events-none"/>
                            <p className="account_util1 pointer-events-none">Pending Reviews</p>
                        </span>
                        <span onClick={(event) => setId(event.target.id)} className="account_util" id="saved">
                            <HeartIcon className="h-5 text-gray-700 pointer-events-none"/>
                            <p className="account_util1 pointer-events-none">Saved Items</p>
                        </span>
                            <span onClick={(event) => setId(event.target.id)} className="account_util" id="credit">
                            <TicketIcon className="h-5 text-gray-700 pointer-events-none"/>
                            <p className="account_util1 pointer-events-none">Wave Credit</p>
                        </span>
                        <span className="account_util border-b border-gray-200">
                            <ClockIcon className="h-5 text-gray-700"/>
                            <p className="account_util1">Recently Reviewed</p>
                        </span>
                        <span className="account_util">
                            <p className="account_util1">Detailst</p>
                        </span>
                        <span className="account_util">
                            <p className="account_util1">Address Book</p>
                        </span>
                        <span className="account_util">
                            <p className="account_util1">Change Password</p>
                        </span>
                        <span className="account_util">
                            <p className="account_util1">Newsletter Preffernces</p>
                        </span>
                        <span className="flex items-center border-t hover:bg-gray-100 hover:cursor-pointer border-gray-200 justify-center py-1 px-5">
                            <p className="text-orange-400 text-sm py-1">LOGOUT</p>
                        </span>
                    </div>
                    {/* </div> */}
                    {/* <div className="flex flex-col "> */}
                    {(id == "inbox") && <Inbox />}
                    {(id == "orders") && <Orders />}
                    {(id == "saved") && <SavedItems />}
                    {(id == "pending") && <Pending />}
                    {(id == "credit") && <WaveCredit />}
                {/* </div> */}
            </main>
        </div>
  );
};

export default orders;

import React from 'react';