import React from 'react';
import { useState } from "react"
import Head from 'next/head'
import MainHeader from '../components/MainHeader';
import Header from '../components/Header';
import SmallHeader from '../components/SmallHeader';
import AccountModal from '../components/AccountModal';
import HelpModal from '../components/HelpModal';


const WaveEats = () => {
    const [close, setClose] = useState(true)
  const [modal, setModal] = useState(true)
    return (
        <div className="bg-gray-100 overflow-x-hidden">
            <Head>
                <title>Wave Food | Cuisins, Drinks, Pizzas, Groceries, Restaurant & Supermarket and so much more</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <SmallHeader />
            <MainHeader setClose={setClose} modal={modal} setModal={setModal} close={close}/>
      {!close && <AccountModal />}
      {!modal && <HelpModal />}
            <main className="w-screen h-screen">
                <div className="w-full flex justify-center mt-6">
                    <h3 className="text-xl font-thin px-3 mx-auto">Order anything and have it delivered in record time.</h3>
                </div>
            </main>
        </div>
    )
}

export default WaveEats;
